# Logging Configuration
logging:
  level: 'INFO'
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: 'logs/inbox_search.log'
# Data Processing Configuration
data:
  output_path: 'data/processed.json'
  input_path: 'data/data.txt'
# Model Config
search:
  model_name: "all-MiniLM-L6-v2"
  top_k: 5